Add opus remux for jellyfin 10.10 and customizable bluetooth device icons
rasmuslos/AmpFin pull request #86
Opened 2024-12-10 09:25 UTC by gnattu

Jellyfin 10.10 introduces remux support for UniversalAudioController, allowing direct copy of the codec without transcoding. This feature is particularly useful for us as the iOS native player can play Opus audio, just not within the Ogg container. This PR adds an opus in mp4 profile when the server version is 10.10 or higher enables the server to directly copy opus during HLS streaming. For downloads, the server will provide an MP4 file with Opus directly copied in the container. I have tested and verified that both streaming and downloads works with all the iOS versions we support (iOS 17 and above).

This also adds a new option that enables users to customize the default Bluetooth device icon rather than to always use the hifi speaker icon. I hope Apple provides an easier way to at least identify their own headphones. The AirPods allow users to rename them, making it impossible to simply add overrides with the route name, as we currently do for some Bluetooth headphones.

2025-01-05 07:27 UTC, perrygoy commented on AmpFinKit/Sources/AFNetwork/HTTP/JellyfinClient.swift
> +            return major >= 10 && minor >= 10;
Forgive the drive-by PR review, but won't this start returning `false` when version 11.0 comes out? At least until 11.10 comes around.

2025-01-05 09:01 UTC, gnattu commented on AmpFinKit/Sources/AFNetwork/HTTP/JellyfinClient.swift
> +            return major >= 10 && minor >= 10;
Yes it will. But from Jellyfin server perspective 11.0 means almost each and every api is broken and the clients must have to accommodate that, which means it should be okay for AmpFin.

2025-01-06 10:01 UTC, rasmuslos commented
Sorry for the late reply, I am currently busy working on ShelfPlayer, but there won't be another AmpFin release until I am finished.

2025-01-06 10:04 UTC, rasmuslos requested changes

2025-01-06 10:04 UTC, rasmuslos commented on AmpFinKit/Sources/AFPlayback/AudioPlayer/AudioPlayer.swift
> +                return UserDefaults.standard.string(forKey: "defaultBTDeviceIcon") ?? "hifispeaker"
You should use `Defaults[.defaultBTDeviceIcon]` instead of the native API

2025-01-06 10:04 UTC, rasmuslos commented on AmpFinKit/Sources/AFNetwork/HTTP/JellyfinClient.swift
> +            return major >= 10 && minor >= 10;
There is already a system to perform these checks: https://github.com/rasmuslos/AmpFin/blob/main/AmpFinKit/Sources/AFNetwork/HTTP/JellyfinClient%2BFeatureFlags.swift

2025-01-09 21:43 UTC, rasmuslos approved these changes

2025-01-09 21:43 UTC, merged

2025-01-09 21:43 UTC, rasmuslos commented
Thanks!